# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from click_up_python_sdk.type.invited_by import InvitedBy
from click_up_python_sdk.type.shared import Shared
from click_up_python_sdk.type.user21 import User21

class RequiredMember7(TypedDict):
    pass

class OptionalMember7(TypedDict, total=False):
    user: User21

    invited_by: InvitedBy

    shared: Shared

class Member7(RequiredMember7, OptionalMember7):
    pass
