# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredProfileInfo(TypedDict):
    display_profile: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    verified_ambassador: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    verified_consultant: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    top_tier_user: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    viewed_verified_ambassador: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    viewed_verified_consultant: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    viewed_top_tier_user: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

class OptionalProfileInfo(TypedDict, total=False):
    pass

class ProfileInfo(RequiredProfileInfo, OptionalProfileInfo):
    pass
