# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from click_up_python_sdk.type.creator import Creator
from click_up_python_sdk.type.folder import Folder
from click_up_python_sdk.type.linked_task import LinkedTask
from click_up_python_sdk.type.model_list import ModelList
from click_up_python_sdk.type.space import Space
from click_up_python_sdk.type.status import Status
from click_up_python_sdk.type.task_assignees import TaskAssignees
from click_up_python_sdk.type.task_checklists import TaskChecklists
from click_up_python_sdk.type.task_tags import TaskTags

RequiredTask = TypedDict("RequiredTask", {
    "tags": TaskTags,

    "id": str,

    "name": str,

    "status": Status,

    "orderindex": str,

    "date_created": str,

    "date_updated": str,

    "date_closed": typing.Union[bool, date, datetime, dict, float, int, list, str, None],

    "creator": Creator,

    "assignees": TaskAssignees,

    "checklists": TaskChecklists,

    "parent": typing.Union[bool, date, datetime, dict, float, int, list, str, None],

    "priority": typing.Union[bool, date, datetime, dict, float, int, list, str, None],

    "due_date": typing.Union[bool, date, datetime, dict, float, int, list, str, None],

    "start_date": typing.Union[bool, date, datetime, dict, float, int, list, str, None],

    "time_estimate": typing.Union[bool, date, datetime, dict, float, int, list, str, None],

    "time_spent": typing.Union[bool, date, datetime, dict, float, int, list, str, None],

    "list": ModelList,

    "folder": Folder,

    "space": Space,

    "linked_tasks": typing.List[LinkedTask],

    "url": str,
    })

OptionalTask = TypedDict("OptionalTask", {
    }, total=False)

class Task(RequiredTask, OptionalTask):
    pass
