# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from click_up_python_sdk.type.custom_role import CustomRole

class RequiredUser21(TypedDict):
    pass

class OptionalUser21(TypedDict, total=False):
    id: int

    username: str

    email: str

    color: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    profilePicture: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    initials: str

    # Owner = 1, Admin = 2, Member = 3, Guest = 4
    role: int

    custom_role: CustomRole

    last_active: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    date_joined: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    date_invited: str

class User21(RequiredUser21, OptionalUser21):
    pass
