# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from click_up_python_sdk.type.health import Health
from click_up_python_sdk.type.webhook_events import WebhookEvents

class RequiredWebhook(TypedDict):
    id: str

    userid: int

    team_id: int

    endpoint: str

    client_id: str

    events: WebhookEvents

    task_id: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    list_id: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    folder_id: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    space_id: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    health: Health

    secret: str

class OptionalWebhook(TypedDict, total=False):
    pass

class Webhook(RequiredWebhook, OptionalWebhook):
    pass
