# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from click_up_python_sdk import ClickUp

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        clickup = ClickUp(
        
                        authorization_token = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(clickup)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
