# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from click_up_python_sdk.pydantic.datum1_tags import Datum1Tags
from click_up_python_sdk.pydantic.task4 import Task4
from click_up_python_sdk.pydantic.task_location import TaskLocation
from click_up_python_sdk.pydantic.task_tag import TaskTag
from click_up_python_sdk.pydantic.user2 import User2

class Datum1(BaseModel):
    tags: Datum1Tags = Field(alias='tags')

    description: str = Field(alias='description')

    id: str = Field(alias='id')

    task: Task4 = Field(alias='task')

    wid: str = Field(alias='wid')

    user: User2 = Field(alias='user')

    billable: bool = Field(alias='billable')

    start: str = Field(alias='start')

    end: str = Field(alias='end')

    duration: str = Field(alias='duration')

    source: str = Field(alias='source')

    at: str = Field(alias='at')

    task_location: TaskLocation = Field(alias='task_location')

    task_tags: typing.List[TaskTag] = Field(alias='task_tags')

    task_url: str = Field(alias='task_url')
    class Config:
        arbitrary_types_allowed = True
