# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class InviteGuestToWorkspacerequest(BaseModel):
    email: str = Field(alias='email')

    can_edit_tags: bool = Field(alias='can_edit_tags')

    can_see_time_spent: bool = Field(alias='can_see_time_spent')

    can_see_time_estimated: bool = Field(alias='can_see_time_estimated')

    can_create_views: bool = Field(alias='can_create_views')

    custom_role_id: int = Field(alias='custom_role_id')
    class Config:
        arbitrary_types_allowed = True
