# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from click_up_python_sdk.pydantic.key_result1_subcategory_ids import KeyResult1SubcategoryIds
from click_up_python_sdk.pydantic.key_result1_task_ids import KeyResult1TaskIds
from click_up_python_sdk.pydantic.last_action1 import LastAction1
from click_up_python_sdk.pydantic.owner import Owner

class KeyResult1(BaseModel):
    id: str = Field(alias='id')

    goal_id: str = Field(alias='goal_id')

    name: str = Field(alias='name')

    type: str = Field(alias='type')

    unit: str = Field(alias='unit')

    creator: int = Field(alias='creator')

    date_created: str = Field(alias='date_created')

    goal_pretty_id: str = Field(alias='goal_pretty_id')

    percent_completed: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='percent_completed')

    completed: bool = Field(alias='completed')

    task_ids: KeyResult1TaskIds = Field(alias='task_ids')

    subcategory_ids: KeyResult1SubcategoryIds = Field(alias='subcategory_ids')

    owners: typing.List[Owner] = Field(alias='owners')

    last_action: LastAction1 = Field(alias='last_action')
    class Config:
        arbitrary_types_allowed = True
