# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class LastAction(BaseModel):
    id: str = Field(alias='id')

    key_result_id: str = Field(alias='key_result_id')

    userid: int = Field(alias='userid')

    date_modified: str = Field(alias='date_modified')

    steps_taken: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='steps_taken')

    note: str = Field(alias='note')

    steps_before: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='steps_before')

    steps_current: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='steps_current')
    class Config:
        arbitrary_types_allowed = True
