# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class User7(BaseModel):
    id: int = Field(alias='id')

    username: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='username')

    email: str = Field(alias='email')

    color: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='color')

    profile_picture: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='profilePicture')

    initials: str = Field(alias='initials')

    role: int = Field(alias='role')

    last_active: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='last_active')

    date_joined: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='date_joined')

    date_invited: str = Field(alias='date_invited')
    class Config:
        arbitrary_types_allowed = True
