# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from click_up_python_sdk.pydantic.health import Health
from click_up_python_sdk.pydantic.webhook_events import WebhookEvents

class Webhook(BaseModel):
    id: str = Field(alias='id')

    userid: int = Field(alias='userid')

    team_id: int = Field(alias='team_id')

    endpoint: str = Field(alias='endpoint')

    client_id: str = Field(alias='client_id')

    events: WebhookEvents = Field(alias='events')

    task_id: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='task_id')

    list_id: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='list_id')

    folder_id: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='folder_id')

    space_id: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='space_id')

    health: Health = Field(alias='health')

    secret: str = Field(alias='secret')
    class Config:
        arbitrary_types_allowed = True
