# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from click_up_python_sdk import schemas  # noqa: F401


class Features4(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "checklists",
            "time_estimates",
            "time_tracking",
            "due_dates",
            "tags",
        }
        
        class properties:
        
            @staticmethod
            def tags() -> typing.Type['Tags']:
                return Tags
        
            @staticmethod
            def due_dates() -> typing.Type['DueDates']:
                return DueDates
        
            @staticmethod
            def time_tracking() -> typing.Type['TimeTracking']:
                return TimeTracking
        
            @staticmethod
            def time_estimates() -> typing.Type['TimeEstimates']:
                return TimeEstimates
        
            @staticmethod
            def checklists() -> typing.Type['Checklists']:
                return Checklists
        
            @staticmethod
            def custom_fields() -> typing.Type['CustomFields']:
                return CustomFields
        
            @staticmethod
            def remap_dependencies() -> typing.Type['RemapDependencies']:
                return RemapDependencies
        
            @staticmethod
            def dependency_warning() -> typing.Type['DependencyWarning']:
                return DependencyWarning
        
            @staticmethod
            def portfolios() -> typing.Type['Portfolios']:
                return Portfolios
            __annotations__ = {
                "tags": tags,
                "due_dates": due_dates,
                "time_tracking": time_tracking,
                "time_estimates": time_estimates,
                "checklists": checklists,
                "custom_fields": custom_fields,
                "remap_dependencies": remap_dependencies,
                "dependency_warning": dependency_warning,
                "portfolios": portfolios,
            }
    
    checklists: 'Checklists'
    time_estimates: 'TimeEstimates'
    time_tracking: 'TimeTracking'
    due_dates: 'DueDates'
    tags: 'Tags'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tags"]) -> 'Tags': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["due_dates"]) -> 'DueDates': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["time_tracking"]) -> 'TimeTracking': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["time_estimates"]) -> 'TimeEstimates': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["checklists"]) -> 'Checklists': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["custom_fields"]) -> 'CustomFields': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["remap_dependencies"]) -> 'RemapDependencies': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dependency_warning"]) -> 'DependencyWarning': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["portfolios"]) -> 'Portfolios': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["tags", "due_dates", "time_tracking", "time_estimates", "checklists", "custom_fields", "remap_dependencies", "dependency_warning", "portfolios", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tags"]) -> 'Tags': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["due_dates"]) -> 'DueDates': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["time_tracking"]) -> 'TimeTracking': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["time_estimates"]) -> 'TimeEstimates': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["checklists"]) -> 'Checklists': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["custom_fields"]) -> typing.Union['CustomFields', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["remap_dependencies"]) -> typing.Union['RemapDependencies', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dependency_warning"]) -> typing.Union['DependencyWarning', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["portfolios"]) -> typing.Union['Portfolios', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["tags", "due_dates", "time_tracking", "time_estimates", "checklists", "custom_fields", "remap_dependencies", "dependency_warning", "portfolios", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        checklists: 'Checklists',
        time_estimates: 'TimeEstimates',
        time_tracking: 'TimeTracking',
        due_dates: 'DueDates',
        tags: 'Tags',
        custom_fields: typing.Union['CustomFields', schemas.Unset] = schemas.unset,
        remap_dependencies: typing.Union['RemapDependencies', schemas.Unset] = schemas.unset,
        dependency_warning: typing.Union['DependencyWarning', schemas.Unset] = schemas.unset,
        portfolios: typing.Union['Portfolios', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Features4':
        return super().__new__(
            cls,
            *args,
            checklists=checklists,
            time_estimates=time_estimates,
            time_tracking=time_tracking,
            due_dates=due_dates,
            tags=tags,
            custom_fields=custom_fields,
            remap_dependencies=remap_dependencies,
            dependency_warning=dependency_warning,
            portfolios=portfolios,
            _configuration=_configuration,
            **kwargs,
        )

from click_up_python_sdk.model.checklists import Checklists
from click_up_python_sdk.model.custom_fields import CustomFields
from click_up_python_sdk.model.dependency_warning import DependencyWarning
from click_up_python_sdk.model.due_dates import DueDates
from click_up_python_sdk.model.portfolios import Portfolios
from click_up_python_sdk.model.remap_dependencies import RemapDependencies
from click_up_python_sdk.model.tags import Tags
from click_up_python_sdk.model.time_estimates import TimeEstimates
from click_up_python_sdk.model.time_tracking import TimeTracking
