# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from click_up_python_sdk import schemas  # noqa: F401


class Member2(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "date_added",
            "permission_level",
            "profilePicture",
            "color",
            "added_by",
            "initials",
            "id",
            "email",
            "username",
        }
        
        class properties:
            id = schemas.IntSchema
            email = schemas.StrSchema
            username = schemas.StrSchema
            color = schemas.StrSchema
            permission_level = schemas.StrSchema
            date_added = schemas.IntSchema
            added_by = schemas.IntSchema
            initials = schemas.StrSchema
            profilePicture = schemas.StrSchema
            __annotations__ = {
                "id": id,
                "email": email,
                "username": username,
                "color": color,
                "permission_level": permission_level,
                "date_added": date_added,
                "added_by": added_by,
                "initials": initials,
                "profilePicture": profilePicture,
            }
    
    date_added: MetaOapg.properties.date_added
    permission_level: MetaOapg.properties.permission_level
    profilePicture: MetaOapg.properties.profilePicture
    color: MetaOapg.properties.color
    added_by: MetaOapg.properties.added_by
    initials: MetaOapg.properties.initials
    id: MetaOapg.properties.id
    email: MetaOapg.properties.email
    username: MetaOapg.properties.username
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["username"]) -> MetaOapg.properties.username: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["color"]) -> MetaOapg.properties.color: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["permission_level"]) -> MetaOapg.properties.permission_level: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_added"]) -> MetaOapg.properties.date_added: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["added_by"]) -> MetaOapg.properties.added_by: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["initials"]) -> MetaOapg.properties.initials: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["profilePicture"]) -> MetaOapg.properties.profilePicture: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "email", "username", "color", "permission_level", "date_added", "added_by", "initials", "profilePicture", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["username"]) -> MetaOapg.properties.username: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["color"]) -> MetaOapg.properties.color: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["permission_level"]) -> MetaOapg.properties.permission_level: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_added"]) -> MetaOapg.properties.date_added: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["added_by"]) -> MetaOapg.properties.added_by: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["initials"]) -> MetaOapg.properties.initials: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["profilePicture"]) -> MetaOapg.properties.profilePicture: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "email", "username", "color", "permission_level", "date_added", "added_by", "initials", "profilePicture", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        date_added: typing.Union[MetaOapg.properties.date_added, decimal.Decimal, int, ],
        permission_level: typing.Union[MetaOapg.properties.permission_level, str, ],
        profilePicture: typing.Union[MetaOapg.properties.profilePicture, str, ],
        color: typing.Union[MetaOapg.properties.color, str, ],
        added_by: typing.Union[MetaOapg.properties.added_by, decimal.Decimal, int, ],
        initials: typing.Union[MetaOapg.properties.initials, str, ],
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, ],
        email: typing.Union[MetaOapg.properties.email, str, ],
        username: typing.Union[MetaOapg.properties.username, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Member2':
        return super().__new__(
            cls,
            *args,
            date_added=date_added,
            permission_level=permission_level,
            profilePicture=profilePicture,
            color=color,
            added_by=added_by,
            initials=initials,
            id=id,
            email=email,
            username=username,
            _configuration=_configuration,
            **kwargs,
        )
