# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from click_up_python_sdk import schemas  # noqa: F401


class Space13(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "features",
            "private",
            "name",
            "statuses",
            "id",
            "multiple_assignees",
        }
        
        class properties:
            id = schemas.StrSchema
            name = schemas.StrSchema
            private = schemas.BoolSchema
            
            
            class statuses(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Status']:
                        return Status
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Status'], typing.List['Status']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'statuses':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Status':
                    return super().__getitem__(i)
            multiple_assignees = schemas.BoolSchema
        
            @staticmethod
            def features() -> typing.Type['Features4']:
                return Features4
            color = schemas.StrSchema
            avatar = schemas.StrSchema
            admin_can_manage = schemas.BoolSchema
            archived = schemas.BoolSchema
            
            
            class members(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Member']:
                        return Member
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Member'], typing.List['Member']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'members':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Member':
                    return super().__getitem__(i)
            __annotations__ = {
                "id": id,
                "name": name,
                "private": private,
                "statuses": statuses,
                "multiple_assignees": multiple_assignees,
                "features": features,
                "color": color,
                "avatar": avatar,
                "admin_can_manage": admin_can_manage,
                "archived": archived,
                "members": members,
            }
    
    features: 'Features4'
    private: MetaOapg.properties.private
    name: MetaOapg.properties.name
    statuses: MetaOapg.properties.statuses
    id: MetaOapg.properties.id
    multiple_assignees: MetaOapg.properties.multiple_assignees
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["private"]) -> MetaOapg.properties.private: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["statuses"]) -> MetaOapg.properties.statuses: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["multiple_assignees"]) -> MetaOapg.properties.multiple_assignees: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["features"]) -> 'Features4': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["color"]) -> MetaOapg.properties.color: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["avatar"]) -> MetaOapg.properties.avatar: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["admin_can_manage"]) -> MetaOapg.properties.admin_can_manage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["archived"]) -> MetaOapg.properties.archived: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["members"]) -> MetaOapg.properties.members: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "name", "private", "statuses", "multiple_assignees", "features", "color", "avatar", "admin_can_manage", "archived", "members", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["private"]) -> MetaOapg.properties.private: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["statuses"]) -> MetaOapg.properties.statuses: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["multiple_assignees"]) -> MetaOapg.properties.multiple_assignees: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["features"]) -> 'Features4': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["color"]) -> typing.Union[MetaOapg.properties.color, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["avatar"]) -> typing.Union[MetaOapg.properties.avatar, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["admin_can_manage"]) -> typing.Union[MetaOapg.properties.admin_can_manage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["archived"]) -> typing.Union[MetaOapg.properties.archived, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["members"]) -> typing.Union[MetaOapg.properties.members, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "name", "private", "statuses", "multiple_assignees", "features", "color", "avatar", "admin_can_manage", "archived", "members", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        features: 'Features4',
        private: typing.Union[MetaOapg.properties.private, bool, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        statuses: typing.Union[MetaOapg.properties.statuses, list, tuple, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        multiple_assignees: typing.Union[MetaOapg.properties.multiple_assignees, bool, ],
        color: typing.Union[MetaOapg.properties.color, str, schemas.Unset] = schemas.unset,
        avatar: typing.Union[MetaOapg.properties.avatar, str, schemas.Unset] = schemas.unset,
        admin_can_manage: typing.Union[MetaOapg.properties.admin_can_manage, bool, schemas.Unset] = schemas.unset,
        archived: typing.Union[MetaOapg.properties.archived, bool, schemas.Unset] = schemas.unset,
        members: typing.Union[MetaOapg.properties.members, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Space13':
        return super().__new__(
            cls,
            *args,
            features=features,
            private=private,
            name=name,
            statuses=statuses,
            id=id,
            multiple_assignees=multiple_assignees,
            color=color,
            avatar=avatar,
            admin_can_manage=admin_can_manage,
            archived=archived,
            members=members,
            _configuration=_configuration,
            **kwargs,
        )

from click_up_python_sdk.model.features4 import Features4
from click_up_python_sdk.model.member import Member
from click_up_python_sdk.model.status import Status
