# coding: utf-8
"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from click_up_python_sdk.client_custom import ClientCustom
from click_up_python_sdk.configuration import Configuration
from click_up_python_sdk.api_client import ApiClient
from click_up_python_sdk.type_util import copy_signature
from click_up_python_sdk.apis.tags.attachments_api import AttachmentsApi
from click_up_python_sdk.apis.tags.authorization_api import AuthorizationApi
from click_up_python_sdk.apis.tags.comments_api import CommentsApi
from click_up_python_sdk.apis.tags.custom_fields_api import CustomFieldsApi
from click_up_python_sdk.apis.tags.custom_task_types_api import CustomTaskTypesApi
from click_up_python_sdk.apis.tags.folders_api import FoldersApi
from click_up_python_sdk.apis.tags.goals_api import GoalsApi
from click_up_python_sdk.apis.tags.guests_api import GuestsApi
from click_up_python_sdk.apis.tags.lists_api import ListsApi
from click_up_python_sdk.apis.tags.members_api import MembersApi
from click_up_python_sdk.apis.tags.roles_api import RolesApi
from click_up_python_sdk.apis.tags.shared_hierarchy_api import SharedHierarchyApi
from click_up_python_sdk.apis.tags.spaces_api import SpacesApi
from click_up_python_sdk.apis.tags.tags_api import TagsApi
from click_up_python_sdk.apis.tags.task_checklists_api import TaskChecklistsApi
from click_up_python_sdk.apis.tags.task_relationships_api import TaskRelationshipsApi
from click_up_python_sdk.apis.tags.task_templates_api import TaskTemplatesApi
from click_up_python_sdk.apis.tags.tasks_api import TasksApi
from click_up_python_sdk.apis.tags.teams_user_groups_api import TeamsUserGroupsApi
from click_up_python_sdk.apis.tags.teams_workspaces_api import TeamsWorkspacesApi
from click_up_python_sdk.apis.tags.time_tracking_api import TimeTrackingApi
from click_up_python_sdk.apis.tags.time_tracking_legacy_api import TimeTrackingLegacyApi
from click_up_python_sdk.apis.tags.users_api import UsersApi
from click_up_python_sdk.apis.tags.views_api import ViewsApi
from click_up_python_sdk.apis.tags.webhooks_api import WebhooksApi



class ClickUp(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.attachments: AttachmentsApi = AttachmentsApi(api_client)
        self.authorization: AuthorizationApi = AuthorizationApi(api_client)
        self.comments: CommentsApi = CommentsApi(api_client)
        self.custom_fields: CustomFieldsApi = CustomFieldsApi(api_client)
        self.custom_task_types: CustomTaskTypesApi = CustomTaskTypesApi(api_client)
        self.folders: FoldersApi = FoldersApi(api_client)
        self.goals: GoalsApi = GoalsApi(api_client)
        self.guests: GuestsApi = GuestsApi(api_client)
        self.lists: ListsApi = ListsApi(api_client)
        self.members: MembersApi = MembersApi(api_client)
        self.roles: RolesApi = RolesApi(api_client)
        self.shared_hierarchy: SharedHierarchyApi = SharedHierarchyApi(api_client)
        self.spaces: SpacesApi = SpacesApi(api_client)
        self.tags: TagsApi = TagsApi(api_client)
        self.task_checklists: TaskChecklistsApi = TaskChecklistsApi(api_client)
        self.task_relationships: TaskRelationshipsApi = TaskRelationshipsApi(api_client)
        self.task_templates: TaskTemplatesApi = TaskTemplatesApi(api_client)
        self.tasks: TasksApi = TasksApi(api_client)
        self.teams___user_groups: TeamsUserGroupsApi = TeamsUserGroupsApi(api_client)
        self.teams___workspaces: TeamsWorkspacesApi = TeamsWorkspacesApi(api_client)
        self.time_tracking: TimeTrackingApi = TimeTrackingApi(api_client)
        self.time_tracking_(legacy): TimeTrackingLegacyApi = TimeTrackingLegacyApi(api_client)
        self.users: UsersApi = UsersApi(api_client)
        self.views: ViewsApi = ViewsApi(api_client)
        self.webhooks: WebhooksApi = WebhooksApi(api_client)
