# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from click_up_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from click_up_python_sdk.api_response import AsyncGeneratorResponse
from click_up_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from click_up_python_sdk import schemas  # noqa: F401

from click_up_python_sdk.model.gettimeentrieswithinadaterangeresponse import Gettimeentrieswithinadaterangeresponse as GettimeentrieswithinadaterangeresponseSchema

from click_up_python_sdk.type.gettimeentrieswithinadaterangeresponse import Gettimeentrieswithinadaterangeresponse

from ...api_client import Dictionary
from click_up_python_sdk.pydantic.gettimeentrieswithinadaterangeresponse import Gettimeentrieswithinadaterangeresponse as GettimeentrieswithinadaterangeresponsePydantic

# Query params
StartDateSchema = schemas.NumberSchema
EndDateSchema = schemas.NumberSchema
AssigneeSchema = schemas.NumberSchema
IncludeTaskTagsSchema = schemas.BoolSchema
IncludeLocationNamesSchema = schemas.BoolSchema
SpaceIdSchema = schemas.NumberSchema
FolderIdSchema = schemas.NumberSchema
ListIdSchema = schemas.NumberSchema
TaskIdSchema = schemas.StrSchema
CustomTaskIdsSchema = schemas.BoolSchema
TeamIdSchema = schemas.NumberSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'start_date': typing.Union[StartDateSchema, decimal.Decimal, int, float, ],
        'end_date': typing.Union[EndDateSchema, decimal.Decimal, int, float, ],
        'assignee': typing.Union[AssigneeSchema, decimal.Decimal, int, float, ],
        'include_task_tags': typing.Union[IncludeTaskTagsSchema, bool, ],
        'include_location_names': typing.Union[IncludeLocationNamesSchema, bool, ],
        'space_id': typing.Union[SpaceIdSchema, decimal.Decimal, int, float, ],
        'folder_id': typing.Union[FolderIdSchema, decimal.Decimal, int, float, ],
        'list_id': typing.Union[ListIdSchema, decimal.Decimal, int, float, ],
        'task_id': typing.Union[TaskIdSchema, str, ],
        'custom_task_ids': typing.Union[CustomTaskIdsSchema, bool, ],
        'team_id': typing.Union[TeamIdSchema, decimal.Decimal, int, float, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_start_date = api_client.QueryParameter(
    name="start_date",
    style=api_client.ParameterStyle.FORM,
    schema=StartDateSchema,
    explode=True,
)
request_query_end_date = api_client.QueryParameter(
    name="end_date",
    style=api_client.ParameterStyle.FORM,
    schema=EndDateSchema,
    explode=True,
)
request_query_assignee = api_client.QueryParameter(
    name="assignee",
    style=api_client.ParameterStyle.FORM,
    schema=AssigneeSchema,
    explode=True,
)
request_query_include_task_tags = api_client.QueryParameter(
    name="include_task_tags",
    style=api_client.ParameterStyle.FORM,
    schema=IncludeTaskTagsSchema,
    explode=True,
)
request_query_include_location_names = api_client.QueryParameter(
    name="include_location_names",
    style=api_client.ParameterStyle.FORM,
    schema=IncludeLocationNamesSchema,
    explode=True,
)
request_query_space_id = api_client.QueryParameter(
    name="space_id",
    style=api_client.ParameterStyle.FORM,
    schema=SpaceIdSchema,
    explode=True,
)
request_query_folder_id = api_client.QueryParameter(
    name="folder_id",
    style=api_client.ParameterStyle.FORM,
    schema=FolderIdSchema,
    explode=True,
)
request_query_list_id = api_client.QueryParameter(
    name="list_id",
    style=api_client.ParameterStyle.FORM,
    schema=ListIdSchema,
    explode=True,
)
request_query_task_id = api_client.QueryParameter(
    name="task_id",
    style=api_client.ParameterStyle.FORM,
    schema=TaskIdSchema,
    explode=True,
)
request_query_custom_task_ids = api_client.QueryParameter(
    name="custom_task_ids",
    style=api_client.ParameterStyle.FORM,
    schema=CustomTaskIdsSchema,
    explode=True,
)
request_query_team_id2 = api_client.QueryParameter(
    name="team_id",
    style=api_client.ParameterStyle.FORM,
    schema=TeamIdSchema,
    explode=True,
)
# Path params
TeamIdSchema = schemas.NumberSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'team_Id': typing.Union[TeamIdSchema, decimal.Decimal, int, float, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_team_id = api_client.PathParameter(
    name="team_Id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=TeamIdSchema,
    required=True,
)
SchemaFor200ResponseBodyApplicationJson = GettimeentrieswithinadaterangeresponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: Gettimeentrieswithinadaterangeresponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: Gettimeentrieswithinadaterangeresponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_time_entries_within_date_range_mapped_args(
        self,
        team_id: typing.Union[int, float],
        start_date: typing.Optional[typing.Union[int, float]] = None,
        end_date: typing.Optional[typing.Union[int, float]] = None,
        assignee: typing.Optional[typing.Union[int, float]] = None,
        include_task_tags: typing.Optional[bool] = None,
        include_location_names: typing.Optional[bool] = None,
        space_id: typing.Optional[typing.Union[int, float]] = None,
        folder_id: typing.Optional[typing.Union[int, float]] = None,
        list_id: typing.Optional[typing.Union[int, float]] = None,
        task_id: typing.Optional[str] = None,
        custom_task_ids: typing.Optional[bool] = None,
        team_id2: typing.Optional[typing.Union[int, float]] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _path_params = {}
        if start_date is not None:
            _query_params["start_date"] = start_date
        if end_date is not None:
            _query_params["end_date"] = end_date
        if assignee is not None:
            _query_params["assignee"] = assignee
        if include_task_tags is not None:
            _query_params["include_task_tags"] = include_task_tags
        if include_location_names is not None:
            _query_params["include_location_names"] = include_location_names
        if space_id is not None:
            _query_params["space_id"] = space_id
        if folder_id is not None:
            _query_params["folder_id"] = folder_id
        if list_id is not None:
            _query_params["list_id"] = list_id
        if task_id is not None:
            _query_params["task_id"] = task_id
        if custom_task_ids is not None:
            _query_params["custom_task_ids"] = custom_task_ids
        if team_id2 is not None:
            _query_params["team_id"] = team_id2
        if team_id is not None:
            _path_params["team_Id"] = team_id
        args.query = _query_params
        args.path = _path_params
        return args

    async def _aget_time_entries_within_date_range_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Get time entries within a date range
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_team_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_start_date,
            request_query_end_date,
            request_query_assignee,
            request_query_include_task_tags,
            request_query_include_location_names,
            request_query_space_id,
            request_query_folder_id,
            request_query_list_id,
            request_query_task_id,
            request_query_custom_task_ids,
            request_query_team_id2,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/team/{team_Id}/time_entries',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_time_entries_within_date_range_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Get time entries within a date range
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_team_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_start_date,
            request_query_end_date,
            request_query_assignee,
            request_query_include_task_tags,
            request_query_include_location_names,
            request_query_space_id,
            request_query_folder_id,
            request_query_list_id,
            request_query_task_id,
            request_query_custom_task_ids,
            request_query_team_id2,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/team/{team_Id}/time_entries',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetTimeEntriesWithinDateRangeRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_time_entries_within_date_range(
        self,
        team_id: typing.Union[int, float],
        start_date: typing.Optional[typing.Union[int, float]] = None,
        end_date: typing.Optional[typing.Union[int, float]] = None,
        assignee: typing.Optional[typing.Union[int, float]] = None,
        include_task_tags: typing.Optional[bool] = None,
        include_location_names: typing.Optional[bool] = None,
        space_id: typing.Optional[typing.Union[int, float]] = None,
        folder_id: typing.Optional[typing.Union[int, float]] = None,
        list_id: typing.Optional[typing.Union[int, float]] = None,
        task_id: typing.Optional[str] = None,
        custom_task_ids: typing.Optional[bool] = None,
        team_id2: typing.Optional[typing.Union[int, float]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_time_entries_within_date_range_mapped_args(
            team_id=team_id,
            start_date=start_date,
            end_date=end_date,
            assignee=assignee,
            include_task_tags=include_task_tags,
            include_location_names=include_location_names,
            space_id=space_id,
            folder_id=folder_id,
            list_id=list_id,
            task_id=task_id,
            custom_task_ids=custom_task_ids,
            team_id2=team_id2,
        )
        return await self._aget_time_entries_within_date_range_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def get_time_entries_within_date_range(
        self,
        team_id: typing.Union[int, float],
        start_date: typing.Optional[typing.Union[int, float]] = None,
        end_date: typing.Optional[typing.Union[int, float]] = None,
        assignee: typing.Optional[typing.Union[int, float]] = None,
        include_task_tags: typing.Optional[bool] = None,
        include_location_names: typing.Optional[bool] = None,
        space_id: typing.Optional[typing.Union[int, float]] = None,
        folder_id: typing.Optional[typing.Union[int, float]] = None,
        list_id: typing.Optional[typing.Union[int, float]] = None,
        task_id: typing.Optional[str] = None,
        custom_task_ids: typing.Optional[bool] = None,
        team_id2: typing.Optional[typing.Union[int, float]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_time_entries_within_date_range_mapped_args(
            team_id=team_id,
            start_date=start_date,
            end_date=end_date,
            assignee=assignee,
            include_task_tags=include_task_tags,
            include_location_names=include_location_names,
            space_id=space_id,
            folder_id=folder_id,
            list_id=list_id,
            task_id=task_id,
            custom_task_ids=custom_task_ids,
            team_id2=team_id2,
        )
        return self._get_time_entries_within_date_range_oapg(
            query_params=args.query,
            path_params=args.path,
        )

class GetTimeEntriesWithinDateRange(BaseApi):

    async def aget_time_entries_within_date_range(
        self,
        team_id: typing.Union[int, float],
        start_date: typing.Optional[typing.Union[int, float]] = None,
        end_date: typing.Optional[typing.Union[int, float]] = None,
        assignee: typing.Optional[typing.Union[int, float]] = None,
        include_task_tags: typing.Optional[bool] = None,
        include_location_names: typing.Optional[bool] = None,
        space_id: typing.Optional[typing.Union[int, float]] = None,
        folder_id: typing.Optional[typing.Union[int, float]] = None,
        list_id: typing.Optional[typing.Union[int, float]] = None,
        task_id: typing.Optional[str] = None,
        custom_task_ids: typing.Optional[bool] = None,
        team_id2: typing.Optional[typing.Union[int, float]] = None,
        validate: bool = False,
        **kwargs,
    ) -> GettimeentrieswithinadaterangeresponsePydantic:
        raw_response = await self.raw.aget_time_entries_within_date_range(
            team_id=team_id,
            start_date=start_date,
            end_date=end_date,
            assignee=assignee,
            include_task_tags=include_task_tags,
            include_location_names=include_location_names,
            space_id=space_id,
            folder_id=folder_id,
            list_id=list_id,
            task_id=task_id,
            custom_task_ids=custom_task_ids,
            team_id2=team_id2,
            **kwargs,
        )
        if validate:
            return GettimeentrieswithinadaterangeresponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(GettimeentrieswithinadaterangeresponsePydantic, raw_response.body)
    
    
    def get_time_entries_within_date_range(
        self,
        team_id: typing.Union[int, float],
        start_date: typing.Optional[typing.Union[int, float]] = None,
        end_date: typing.Optional[typing.Union[int, float]] = None,
        assignee: typing.Optional[typing.Union[int, float]] = None,
        include_task_tags: typing.Optional[bool] = None,
        include_location_names: typing.Optional[bool] = None,
        space_id: typing.Optional[typing.Union[int, float]] = None,
        folder_id: typing.Optional[typing.Union[int, float]] = None,
        list_id: typing.Optional[typing.Union[int, float]] = None,
        task_id: typing.Optional[str] = None,
        custom_task_ids: typing.Optional[bool] = None,
        team_id2: typing.Optional[typing.Union[int, float]] = None,
        validate: bool = False,
    ) -> GettimeentrieswithinadaterangeresponsePydantic:
        raw_response = self.raw.get_time_entries_within_date_range(
            team_id=team_id,
            start_date=start_date,
            end_date=end_date,
            assignee=assignee,
            include_task_tags=include_task_tags,
            include_location_names=include_location_names,
            space_id=space_id,
            folder_id=folder_id,
            list_id=list_id,
            task_id=task_id,
            custom_task_ids=custom_task_ids,
            team_id2=team_id2,
        )
        if validate:
            return GettimeentrieswithinadaterangeresponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(GettimeentrieswithinadaterangeresponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        team_id: typing.Union[int, float],
        start_date: typing.Optional[typing.Union[int, float]] = None,
        end_date: typing.Optional[typing.Union[int, float]] = None,
        assignee: typing.Optional[typing.Union[int, float]] = None,
        include_task_tags: typing.Optional[bool] = None,
        include_location_names: typing.Optional[bool] = None,
        space_id: typing.Optional[typing.Union[int, float]] = None,
        folder_id: typing.Optional[typing.Union[int, float]] = None,
        list_id: typing.Optional[typing.Union[int, float]] = None,
        task_id: typing.Optional[str] = None,
        custom_task_ids: typing.Optional[bool] = None,
        team_id2: typing.Optional[typing.Union[int, float]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_time_entries_within_date_range_mapped_args(
            team_id=team_id,
            start_date=start_date,
            end_date=end_date,
            assignee=assignee,
            include_task_tags=include_task_tags,
            include_location_names=include_location_names,
            space_id=space_id,
            folder_id=folder_id,
            list_id=list_id,
            task_id=task_id,
            custom_task_ids=custom_task_ids,
            team_id2=team_id2,
        )
        return await self._aget_time_entries_within_date_range_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def get(
        self,
        team_id: typing.Union[int, float],
        start_date: typing.Optional[typing.Union[int, float]] = None,
        end_date: typing.Optional[typing.Union[int, float]] = None,
        assignee: typing.Optional[typing.Union[int, float]] = None,
        include_task_tags: typing.Optional[bool] = None,
        include_location_names: typing.Optional[bool] = None,
        space_id: typing.Optional[typing.Union[int, float]] = None,
        folder_id: typing.Optional[typing.Union[int, float]] = None,
        list_id: typing.Optional[typing.Union[int, float]] = None,
        task_id: typing.Optional[str] = None,
        custom_task_ids: typing.Optional[bool] = None,
        team_id2: typing.Optional[typing.Union[int, float]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_time_entries_within_date_range_mapped_args(
            team_id=team_id,
            start_date=start_date,
            end_date=end_date,
            assignee=assignee,
            include_task_tags=include_task_tags,
            include_location_names=include_location_names,
            space_id=space_id,
            folder_id=folder_id,
            list_id=list_id,
            task_id=task_id,
            custom_task_ids=custom_task_ids,
            team_id2=team_id2,
        )
        return self._get_time_entries_within_date_range_oapg(
            query_params=args.query,
            path_params=args.path,
        )

