# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from click_up_python_sdk.paths.oauth_token.post import GetAccessToken
from click_up_python_sdk.paths.team.get import GetWorkspaceList
from click_up_python_sdk.paths.user.get import ViewAccountDetails
from click_up_python_sdk.apis.tags.authorization_api_raw import AuthorizationApiRaw


class AuthorizationApi(
    GetAccessToken,
    GetWorkspaceList,
    ViewAccountDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AuthorizationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AuthorizationApiRaw(api_client)
