# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from click_up_python_sdk.paths.list_list_id_task.post import CreateNewTask
from click_up_python_sdk.paths.team_team_id_task.get import FilterTeamTasks
from click_up_python_sdk.paths.list_list_id_task.get import GetListTasks
from click_up_python_sdk.paths.task_task_id.get import GetTaskDetails
from click_up_python_sdk.paths.task_task_id_time_in_status.get import GetTimeInStatus
from click_up_python_sdk.paths.task_bulk_time_in_status_task_ids.get import GetTimeInStatusBulk
from click_up_python_sdk.paths.task_task_id.delete import RemoveTaskById
from click_up_python_sdk.paths.task_task_id.put import UpdateTaskFields
from click_up_python_sdk.apis.tags.tasks_api_raw import TasksApiRaw


class TasksApi(
    CreateNewTask,
    FilterTeamTasks,
    GetListTasks,
    GetTaskDetails,
    GetTimeInStatus,
    GetTimeInStatusBulk,
    RemoveTaskById,
    UpdateTaskFields,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TasksApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TasksApiRaw(api_client)
