# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from click_up_python_sdk.paths.team_team_id_time_entries_tags.post import AddTagsFromTimeEntries
from click_up_python_sdk.paths.team_team_id_time_entries_tags.put import ChangeTagNames
from click_up_python_sdk.paths.team_team_id_time_entries.post import CreateTimeEntry
from click_up_python_sdk.paths.team_team_id_time_entries_tags.get import GetAllTagsFromTimeEntries
from click_up_python_sdk.paths.team_team_id_time_entries_current.get import GetCurrentTimeEntry
from click_up_python_sdk.paths.team_team_id_time_entries_timer_id.get import GetSingleTimeEntry
from click_up_python_sdk.paths.team_team_id_time_entries.get import GetTimeEntriesWithinDateRange
from click_up_python_sdk.paths.team_team_id_time_entries_timer_id_history.get import GetTimeEntryHistory
from click_up_python_sdk.paths.team_team_id_time_entries_timer_id.delete import RemoveEntry
from click_up_python_sdk.paths.team_team_id_time_entries_tags.delete import RemoveTagsFromTimeEntries
from click_up_python_sdk.paths.team_team_id_time_entries_start.post import StartTimer
from click_up_python_sdk.paths.team_team_id_time_entries_stop.post import StopTimeEntry
from click_up_python_sdk.paths.team_team_id_time_entries_timer_id.put import UpdateTimeEntryDetails
from click_up_python_sdk.apis.tags.time_tracking_api_raw import TimeTrackingApiRaw


class TimeTrackingApi(
    AddTagsFromTimeEntries,
    ChangeTagNames,
    CreateTimeEntry,
    GetAllTagsFromTimeEntries,
    GetCurrentTimeEntry,
    GetSingleTimeEntry,
    GetTimeEntriesWithinDateRange,
    GetTimeEntryHistory,
    RemoveEntry,
    RemoveTagsFromTimeEntries,
    StartTimer,
    StopTimeEntry,
    UpdateTimeEntryDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TimeTrackingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TimeTrackingApiRaw(api_client)
