# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from click_up_python_sdk.paths.folder_folder_id_view.post import AddViewToFolderRaw
from click_up_python_sdk.paths.list_list_id_view.post import AddViewToListRaw
from click_up_python_sdk.paths.space_space_id_view.post import AddViewToSpaceRaw
from click_up_python_sdk.paths.team_team_id_view.post import CreateWorkspaceViewEverythingLevelRaw
from click_up_python_sdk.paths.view_view_id.delete import DeleteViewByIdRaw
from click_up_python_sdk.paths.folder_folder_id_view.get import FolderViewsGetRaw
from click_up_python_sdk.paths.team_team_id_view.get import GetEverythingLevelRaw
from click_up_python_sdk.paths.list_list_id_view.get import GetListViewsRaw
from click_up_python_sdk.paths.view_view_id_task.get import GetTasksInViewRaw
from click_up_python_sdk.paths.view_view_id.get import GetViewInfoRaw
from click_up_python_sdk.paths.space_space_id_view.get import SpaceViewsGetRaw
from click_up_python_sdk.paths.view_view_id.put import UpdateViewDetailsRaw


class ViewsApiRaw(
    AddViewToFolderRaw,
    AddViewToListRaw,
    AddViewToSpaceRaw,
    CreateWorkspaceViewEverythingLevelRaw,
    DeleteViewByIdRaw,
    FolderViewsGetRaw,
    GetEverythingLevelRaw,
    GetListViewsRaw,
    GetTasksInViewRaw,
    GetViewInfoRaw,
    SpaceViewsGetRaw,
    UpdateViewDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
