# coding: utf-8

"""
    ClickUp API Reference

    This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from click_up_python_sdk.paths.folder_folder_id_view.post import AddViewToFolder
from click_up_python_sdk.paths.list_list_id_view.post import AddViewToList
from click_up_python_sdk.paths.space_space_id_view.post import AddViewToSpace
from click_up_python_sdk.paths.team_team_id_view.post import CreateWorkspaceViewEverythingLevel
from click_up_python_sdk.paths.view_view_id.delete import DeleteViewById
from click_up_python_sdk.paths.folder_folder_id_view.get import FolderViewsGet
from click_up_python_sdk.paths.team_team_id_view.get import GetEverythingLevel
from click_up_python_sdk.paths.list_list_id_view.get import GetListViews
from click_up_python_sdk.paths.view_view_id_task.get import GetTasksInView
from click_up_python_sdk.paths.view_view_id.get import GetViewInfo
from click_up_python_sdk.paths.space_space_id_view.get import SpaceViewsGet
from click_up_python_sdk.paths.view_view_id.put import UpdateViewDetails
from click_up_python_sdk.apis.tags.views_api_raw import ViewsApiRaw


class ViewsApi(
    AddViewToFolder,
    AddViewToList,
    AddViewToSpace,
    CreateWorkspaceViewEverythingLevel,
    DeleteViewById,
    FolderViewsGet,
    GetEverythingLevel,
    GetListViews,
    GetTasksInView,
    GetViewInfo,
    SpaceViewsGet,
    UpdateViewDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ViewsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ViewsApiRaw(api_client)
